# Generated by Django 2.0 on 2019-08-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MAC_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='姓名')),
                ('team', models.CharField(max_length=30, verbose_name='所属团队')),
                ('outsourcing_company', models.CharField(max_length=30, verbose_name='外部公司')),
                ('floor', models.CharField(max_length=20, verbose_name='楼层')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号')),
                ('machine_type', models.CharField(blank=True, max_length=50, verbose_name='设备类型')),
                ('machine_num', models.CharField(blank=True, max_length=50, verbose_name='设备编号')),
                ('interface', models.CharField(max_length=10, verbose_name='网口号')),
                ('mac_addr', models.CharField(max_length=30, unique=True, verbose_name='MAC地址')),
                ('ip_addr', models.CharField(max_length=20, unique=True, verbose_name='IP地址')),
                ('remark', models.TextField(blank=True, max_length=250, verbose_name='备注')),
                ('state', models.CharField(blank=True, max_length=10, verbose_name='状态')),
                ('left_time', models.CharField(max_length=20, verbose_name='到期时间')),
            ],
            options={
                'verbose_name_plural': 'MAC地址分配列表',
            },
        ),
    ]
